### ISSUE TITLE
Fix git-describe version to 4.1.0

### ISSUE THREAD

**Issue by cmeury** [w11k/angular-git-info#6]
Currently, it uses `latest`, should probably fix it to the latest published one `4.1.0`?

**Comment by kaihenzler** [comment]
We are trying to resolve the latest version. "latest" is only the fallback value. I'm not quite sure why git-describe does not resolve to 4.1.0

see: https://github.com/w11k/angular-git-info/blob/a76c8e976730539dd7399872e6b0ff076e4205ec/src/utility/util.ts#L95

**Comment by kaihenzler** [comment]
@cmeury It's been a while but should work now with version `1.1.2` of this plugin
